export {default as HomePage} from './HomePage/HomePage'
export{default as Header} from '../components/Header/Header'
export {default as Tours} from './Tours/Tours'
export {default as TourDetails} from './TourDetails/TourDetails'
export {default as TourHighlights} from '../components/TourHighlights/TourHighlights'
export {default as ItenarySchedule} from '../components/ItenarySchedule/ItenarySchedule'
export {default as BookingDetails} from './BookingDetails/BookingDetails'