export{default as PopularSearches} from './PopularSearches/PopularSearches'
export {default as Tour} from './Tour/Tour'
export {LoadingSpinner} from './LoadingSpinner/LoadingSpinner'
export {default as CustomButton} from './CustomButton/CustomButton'
export {default as TourImages} from './TourImages/TourImages'
export {default as TourHighlightDescription} from './TourHighlightDescription/TourHighlightDescription'
export {default as ItenaryDaySchedule} from './DaySchedule/ItenaryDaySchedule'
export {default as PopUpNotification} from './popUpNotification/PopUpNotification'